#### **Trabalho de Processamento de Big Data | Licenciatura em Ciência de Dados 2023/24 | CDB1**

Docente: João Oliveira<br><br>

- David Franco, nº110733

- Felipe Pereira, nº110861

- João Dias, nº110305

- Samuel Ricardo, nº110884<br><br>

https://www.kaggle.com/datasets/PROPPG-PPG/hourly-weather-surface-brazil-southeast-region

*Version 9 (10.11 GB) | Created by John Holz | Data Update 2023/01/30*

# Data Import and Cleaning

## Problem formulation

Neste notebook, procedemos à realização das operações do processo ETL (extração, transformação e processamento). Este processo é essencial para fazer a integração dos dados, sendo organizado e concatenado num único conjunto de dados que esteja pronto para armazenamento e análise numa plataforma de big data.

No nosso caso, os dados serão armazenados localmente no formato parquet, sendo esta uma forma eficiente para leitura e escrita de grandes volumes de dados. Os principais pontos são:

- `Extração`: Importar os dados do dataset escolhido *(Climate Weather Surface of Brazil - Hourly)*.
- `Transformação`: Limpar os dados, tratar valores omissos, realizar ajustes para garantir a qualidade dos dados.
- `Processamento`: Organizar e armazenar os dados trabalhados no formato parquet de forma a poderem ser utilizados nos modelos de machine learning que iremos desenvolver nas etapas seguintes.

Este processo garante que os dados utilizados nos modelos de previsão de temperatura e precipitação sejam de alta qualidade e estejam prontos para análises detalhadas e precisas.

### Setup inicial

In [50]:
from pyspark.sql import SparkSession
from pyspark.sql.types import *
import pyspark.sql.functions as F
from pyspark.sql.functions import col, count, date_format, sum as spark_sum, when

import pandas as pd  
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Create the Spark session

spark = SparkSession.builder \
    .appName("WeatherBrazil") \
    .config("spark.sql.shuffle.partitions", 512) \
    .config("spark.driver.memory", "4g") \
    .config("spark.executor.memory", "4g") \
    .getOrCreate()

In [3]:
spark

### Utils

In [4]:
def compute_nulls_and_uniques(df, cols):
    total = df.count()
    results = []
    for cl in cols:
        knulls = df.select(cl).filter(F.col(cl).isNull()).count()
        knullsperc = knulls / total
        knans = df.select(cl).filter(F.isnan(cl)).count()
        knansperc = knans / total
        kuniques = df.select(cl).distinct().count()
        kuniquesperc = kuniques / total
        results.append(Row(feature = cl, count_nulls = knulls, percentage_nulls = knullsperc,
                           count_nans = knans, percentage_nans = knansperc,
                           count_uniques = kuniques, percentage_uniques = kuniquesperc))

    return spark.createDataFrame(results)

Esta função calcula e retorna o número de valores nulos, NaNs e únicos para cada coluna num DataFrame.

### Coleção de dados inicial

In [5]:
pwd

'/home/jovyan/code/trabalho'

In [6]:
! head -n 3 ./datasets_originais/central_west.csv

"index","Data","Hora","PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)","PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)","PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)","RADIACAO GLOBAL (Kj/m²)","TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)","TEMPERATURA DO PONTO DE ORVALHO (°C)","TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)","UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)","UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)","UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)","region","state","station","station_code","latitude","longitude","height"
138998,"2017-12-20","14:00",0.0,899.6,900.0,899.6,3391,26.5,17.7,26.5,24.4,18.3,16.5,65,57,59,39,9.6,3.9,CO,DF,PARANOA (COOPA-DF),A047,-16.01111111,-47.5575,1043.0
138999,"2017-12-20

In [7]:
! head -n 3 ./datasets_originais/north.csv

"index","Data","Hora","PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)","PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)","PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)","RADIACAO GLOBAL (Kj/m²)","TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)","TEMPERATURA DO PONTO DE ORVALHO (°C)","TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)","UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)","UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)","UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)","region","state","station","station_code","latitude","longitude","height"
0,"2000-05-09","00:00",-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999,-9999,-9999,-9999.0,-9999.0,N,AM,MANAUS,A101,-3.10333333,-60.

In [8]:
! head -n 3 ./datasets_originais/northeast.csv

"index","Data","Hora","PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)","PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)","PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)","RADIACAO GLOBAL (Kj/m²)","TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)","TEMPERATURA DO PONTO DE ORVALHO (°C)","TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)","UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)","UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)","UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)","region","state","station","station_code","latitude","longitude","height"
0,"2000-05-13","00:00",-9999.0,-9999,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999,-9999,-9999,-9999.0,-9999.0,NE,BA,SALVADOR,A401,-13.01666666,-3

In [9]:
! head -n 3 ./datasets_originais/south.csv

"index","Data","Hora","PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)","PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)","PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)","RADIACAO GLOBAL (Kj/m²)","TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)","TEMPERATURA DO PONTO DE ORVALHO (°C)","TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)","UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)","UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)","UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)","region","state","station","station_code","latitude","longitude","height"
0,"2000-09-22","00:00",-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999,-9999,-9999,-9999.0,-9999.0,S,RS,PORTO ALEGRE,A801,-30.05,-51

In [10]:
! head -n 3 ./datasets_originais/southeast.csv

"index","Data","Hora","PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)","PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)","PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)","RADIACAO GLOBAL (Kj/m²)","TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)","TEMPERATURA DO PONTO DE ORVALHO (°C)","TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)","TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)","UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)","UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)","UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)","region","state","station","station_code","latitude","longitude","height"
0,"2000-05-07","00:00",-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999,-9999,-9999,-9999.0,-9999.0,SE,RJ,ECOLOGIA AGRICOLA,A601,-22.

In [11]:
! head -n 3 ./datasets_originais/stations.csv

"station","region","state","station_code","first date","height","longitude","latitude"
QUEIMADAS,NE,BA,A436,"2008-05-23",315.0,-39.61694443,-10.984645
MACAU,NE,RN,A317,"2007-01-06",32.0,-36.57305554,-5.15111111


Estes comandos exibem as 3 primeiras linhas de cada arquivo. Isto é útil para visualizar a estrutura e os dados iniciais.

### Leitura dos datasets

In [12]:
data_dir = data_dir = "./datasets_originais/"

In [13]:
file_path = data_dir + "central_west.csv"
df_central_west = spark.read.csv(file_path, header="true", inferSchema="true", sep=',')

In [14]:
file_path = data_dir + "north.csv"
df_north = spark.read.csv(file_path, header="true", inferSchema="true", sep=',')

In [15]:
file_path = data_dir + "northeast.csv"
df_northeast = spark.read.csv(file_path, header="true", inferSchema="true", sep=',')

In [16]:
file_path = data_dir + "south.csv"
df_south = spark.read.csv(file_path, header="true", inferSchema="true", sep=',')

In [17]:
file_path = data_dir + "southeast.csv"
df_southeast = spark.read.csv(file_path, header="true", inferSchema="true", sep=',')

In [18]:
file_path = data_dir + "stations.csv"
df_stations = spark.read.csv(file_path, header="true", inferSchema="true", sep=',')

Leram-se os arquivos com as informações meteorológicas relativas às regiões do Brasil.

### Verificar os dados e a estrutura

#### Tratamento do Central West

In [19]:
# Schema, show e count do DataFrame de Central West 

df_central_west.printSchema()
df_central_west.show(5, truncate=False) 
df_central_west.count()

root
 |-- index: integer (nullable = true)
 |-- Data: date (nullable = true)
 |-- Hora: timestamp (nullable = true)
 |-- PRECIPITAÇÃO TOTAL, HORÁRIO (mm): double (nullable = true)
 |-- PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB): double (nullable = true)
 |-- PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- RADIACAO GLOBAL (Kj/m²): integer (nullable = true)
 |-- TEMPERATURA DO AR - BULBO SECO, HORARIA (°C): double (nullable = true)
 |-- TEMPERATURA DO PONTO DE ORVALHO (°C): double (nullable = true)
 |-- TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- UMIDADE REL. MAX. NA HORA ANT. (AUT) (%): integer (nullable = t

11427120

Estes comandos são usados para exibir a estrutura, as primeiras 5 linhas e o total de linhas do dataframe, proporcionando uma visão rápida da estrutura, dos dados iniciais e da quantidade de linhas do dataframe.

In [20]:
# renomear as colunas
new_column_names = [
    "Index",
    "Date",
    "Hour",
    "TotalHourlyPrecipitationMm",
    "HourlyStationLevelAtmosphericPressureMb",
    "LastHourMaxAtmosphericPressureMb",
    "LastHourMinAtmosphericPressureMb",
    "GlobalRadiationKjM2",
    "HourlyDryBulbAirTemperatureC",
    "DewPointTemperatureC",
    "LastHourMaxTemperatureC",
    "LastHourMinTemperatureC",
    "LastHourMaxDewPointTemperatureC",
    "LastHourMinDewPointTemperatureC",
    "LastHourMaxRelativeHumidityPercentage",
    "LastHourMinRelativeHumidityPercentage",
    "HourlyRelativeHumidityPercentage",
    "HourlyWindDirectionRadiusDegrees",
    "MaximumWindGustMs",
    "HourlyWindSpeedMs",
    "Region",
    "State",
    "Station",
    "StationCode",
    "Latitude",
    "Longitude",
    "Height"
]

df_central_west = df_central_west.toDF(*new_column_names)

Foram renomeadas as colunas de forma a obedecer a uma estrutura que não implique com a leitura das mesmas.

In [21]:
df_central_west = df_central_west.withColumn("Hour", date_format("Hour", "HH:mm"))

Este comando ajusta o tipo de dados da coluna "Hora" , removendo a parte da data que foi adicionada durante a importação para o Spark e mantendo apenas o formato de hora no estilo "HH:mm".

In [23]:
cols_to_check = [col for col in df_central_west.columns if col not in ["Index", "Date", "Hour"]]

df_central_west_nulls_uniques = compute_nulls_and_uniques(df_central_west, cols_to_check)

Este chunk de código cria uma lista de colunas `cols_to_check`, excluindo as colunas "Index", "Date" e "Hour", e em seguida, chama a função `compute_nulls_and_uniques` para calcular valores nulos e únicos nas colunas selecionadas.

In [24]:
df_central_west_nulls_uniques.show(n=30)

+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|             feature|count_nulls|percentage_nulls|count_nans|percentage_nans|count_uniques|  percentage_uniques|
+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|TotalHourlyPrecip...|          0|             0.0|         0|            0.0|          370| 3.23791121472427E-5|
|HourlyStationLeve...|          0|             0.0|         0|            0.0|         1605|1.404553378279041...|
|LastHourMaxAtmosp...|          0|             0.0|         0|            0.0|         1701|1.488564047634049...|
|LastHourMinAtmosp...|          0|             0.0|         0|            0.0|         1692|1.480688047382017...|
| GlobalRadiationKjM2|          0|             0.0|         0|            0.0|        29575|0.002588141193931...|
|HourlyDryBulbAirT...|          0|             0.0|         0|            0.0|          

Exibe as primeiras 30 linhas do dataframe `df_central_west_nulls_uniques`, fornecendo informações sobre valores nulos e únicos para as colunas selecionadas.

In [15]:
# verificar as instâncias duplicadas
df_central_west.dropDuplicates().count()

11427120

Uma vez que este valor se manteve igual, não foram encontradas instâncias duplicadas.

In [22]:
# summary stats para verificar outliers
cols_num = [
 'TotalHourlyPrecipitationMm',
 'HourlyStationLevelAtmosphericPressureMb',
 'LastHourMaxAtmosphericPressureMb',
 'LastHourMinAtmosphericPressureMb',
 'GlobalRadiationKjM2',
 'HourlyDryBulbAirTemperatureC',
 'DewPointTemperatureC',
 'LastHourMaxTemperatureC',
 'LastHourMinTemperatureC',
 'LastHourMaxDewPointTemperatureC',
 'LastHourMinDewPointTemperatureC',
 'LastHourMaxRelativeHumidityPercentage',
 'LastHourMinRelativeHumidityPercentage',
 'HourlyRelativeHumidityPercentage',
 'HourlyWindDirectionRadiusDegrees',
 'MaximumWindGustMs',
 'HourlyWindSpeedMs',
 'Height']
summary_stats = df_central_west.select(cols_num).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                     count                 mean  \
TotalHourlyPrecipitationMm               11427120  -1783.1188566495225   
HourlyStationLevelAtmosphericPressureMb  11427120   -530.6894289287202   
LastHourMaxAtmosphericPressureMb         11427120   -534.5709728873072   
LastHourMinAtmosphericPressureMb         11427120   -536.0151633744968   
GlobalRadiationKjM2                      11427120   -4589.726086800523   
HourlyDryBulbAirTemperatureC             11427120  -1281.0137210425646   
DewPointTemperatureC                     11427120  -1463.8416488844114   
LastHourMaxTemperatureC                  11427120  -1286.5708290540115   
LastHourMinTemperatureC                  11427120  -1288.5510757040934   
LastHourMaxDewPointTemperatureC          11427120  -1465.9391088830844   
LastHourMinDewPointTemperatureC          11427120  -1472.7705189409053   
LastHourMaxRelativeHumidityPercentage    11427120  -1411.1873082631494   
LastHourMinRelativeHumidityPercentage    11427120  -1420.9594396488353   
HourlyRelativeHumidityPercentage         11427120   -1409.337669071472   
HourlyWindDirectionRadiusDegrees         11427120   -1341.597854402509   
MaximumWindGustMs                        11427120  -1416.3460714861965   
HourlyWindSpeedMs                        11427120  -1408.0839189663577   
Height                                   11427120   504.53519387572163   

summary                                              stddev      min    25%  \
TotalHourlyPrecipitationMm                3827.688372063957  -9999.0    0.0   
HourlyStationLevelAtmosphericPressureMb   3750.987412483837  -9999.0  923.3   
LastHourMaxAtmosphericPressureMb         3755.4394535228616  -9999.0  923.4   
LastHourMinAtmosphericPressureMb          3756.223400667947  -9999.0  922.8   
GlobalRadiationKjM2                        5970.79602161803    -9999  -9999   
HourlyDryBulbAirTemperatureC             3373.2470075854244  -9999.0   19.2   
DewPointTemperatureC                     3555.3765012405474  -9999.0   10.6   
LastHourMaxTemperatureC                  3380.2724200282432  -9999.0   19.7   
LastHourMinTemperatureC                  3380.6115513463214  -9999.0   18.6   
LastHourMaxDewPointTemperatureC            3558.14952559601  -9999.0   11.3   
LastHourMinDewPointTemperatureC           3563.554897679916  -9999.0   10.0   
LastHourMaxRelativeHumidityPercentage    3569.1851910397677    -9999     44   
LastHourMinRelativeHumidityPercentage    3571.4878655547795    -9999     36   
HourlyRelativeHumidityPercentage         3563.6595491929074    -9999     40   
HourlyWindDirectionRadiusDegrees          3619.070979231765    -9999     40   
MaximumWindGustMs                        3491.8530060098315  -9999.0    1.3   
HourlyWindSpeedMs                        3480.1332485705643  -9999.0    0.0   
Height                                   277.65587785012667      5.0  313.0   

summary                                    50%    75%     max  
TotalHourlyPrecipitationMm                 0.0    0.0    96.0  
HourlyStationLevelAtmosphericPressureMb  955.3  974.1  1028.8  
LastHourMaxAtmosphericPressureMb         955.6  974.4  1030.6  
LastHourMinAtmosphericPressureMb         954.9  973.8  1028.1  
GlobalRadiationKjM2                      -9999   1125   48898  
HourlyDryBulbAirTemperatureC              22.9   26.9    45.0  
DewPointTemperatureC                      17.3   20.5    44.8  
LastHourMaxTemperatureC                   23.5   27.9    45.0  
LastHourMinTemperatureC                   22.4   26.0    45.0  
LastHourMaxDewPointTemperatureC           17.9   21.0    44.9  
LastHourMinDewPointTemperatureC           16.8   20.0    44.7  
LastHourMaxRelativeHumidityPercentage       71     88     100  
LastHourMinRelativeHumidityPercentage       62     83     100  
HourlyRelativeHumidityPercentage            67     86     100  
HourlyWindDirectionRadiusDegrees           125    238     360  
MaximumWindGustMs                          3.4    5.7    49.4  
Hou

Aqui são calculadas as *summary stats* para as colunas numéricas, com o objetivo de verificar a presença de outliers.

In [24]:
# Inicializa uma lista para armazenar os resultados
resultados = []

# Itera sobre todas as colunas e conta as ocorrências de -9999
for coluna in cols_num:
    contagem = df_central_west.select(spark_sum(when(col(coluna) == -9999, 1).otherwise(0)).alias(coluna)).collect()[0][coluna]
    resultados.append((coluna, contagem))

# Cria um DataFrame a partir dos resultados
resultado_df = spark.createDataFrame(resultados, ["Coluna", "Contagem_de_-9999"])

# Mostra o DataFrame de resultados
resultado_df.show()

+--------------------+-----------------+
|              Coluna|Contagem_de_-9999|
+--------------------+-----------------+
|TotalHourlyPrecip...|          2037944|
|HourlyStationLeve...|          1550070|
|LastHourMaxAtmosp...|          1554352|
|LastHourMinAtmosp...|          1555323|
| GlobalRadiationKjM2|          6074754|
|HourlyDryBulbAirT...|          1488024|
|DewPointTemperatureC|          1689639|
|LastHourMaxTemper...|          1495074|
|LastHourMinTemper...|          1495926|
|LastHourMaxDewPoi...|          1692594|
|LastHourMinDewPoi...|          1699292|
|LastHourMaxRelati...|          1683063|
|LastHourMinRelati...|          1688184|
|HourlyRelativeHum...|          1678001|
|HourlyWindDirecti...|          1698790|
|   MaximumWindGustMs|          1622867|
|   HourlyWindSpeedMs|          1610863|
|              Height|                0|
+--------------------+-----------------+



Verificámos que havia muitas observações com o valor -9999, que foram usadas sobre os valores omissos. No entanto, para garantir que esses valores não influenciem negativamente a estrutura e o padrão da nossa regressão, decidimos removê-los. No nosso caso, vamos proceder à eliminação da coluna `GlobalRadiation` e, nas outras colunas, vamos eliminar todas as observações que contêm o valor -9999. Esta abordagem assegura que a qualidade dos dados não comprometerá a precisão e a robustez dos nossos modelos preditivos.

In [40]:
# drop da coluna GlobalRadiationKjM2 por ter muitos missings
df_central_west = df_central_west.drop("GlobalRadiationKjM2")

In [47]:
# remover linhas com valor -9999 em qualquer coluna
df_central_west = df_central_west.filter(~col("TotalHourlyPrecipitationMm").eqNullSafe(-9999) &
                                                  ~col("HourlyStationLevelAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMinAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("HourlyDryBulbAirTemperatureC").eqNullSafe(-9999) &
                                                  ~col("DewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("LastHourMinRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyWindDirectionRadiusDegrees").eqNullSafe(-9999) &
                                                  ~col("MaximumWindGustMs").eqNullSafe(-9999) &
                                                  ~col("HourlyWindSpeedMs").eqNullSafe(-9999))

In [48]:
df_central_west.printSchema()
df_central_west.show()
df_central_west.count()

root
 |-- Index: integer (nullable = true)
 |-- Date: date (nullable = true)
 |-- Hour: string (nullable = true)
 |-- TotalHourlyPrecipitationMm: double (nullable = true)
 |-- HourlyStationLevelAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMaxAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMinAtmosphericPressureMb: double (nullable = true)
 |-- HourlyDryBulbAirTemperatureC: double (nullable = true)
 |-- DewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxTemperatureC: double (nullable = true)
 |-- LastHourMinTemperatureC: double (nullable = true)
 |-- LastHourMaxDewPointTemperatureC: double (nullable = true)
 |-- LastHourMinDewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxRelativeHumidityPercentage: integer (nullable = true)
 |-- LastHourMinRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyWindDirectionRadiusDegrees: integer (nullable = true)
 |-- Maximum

8888790

O número de instâncias reduziu de 11427120 para 8888790 após a eliminação das observações com o valor -9999.

In [49]:
# summary stats após transformações
cols_num_2 = [
 'TotalHourlyPrecipitationMm',
 'HourlyStationLevelAtmosphericPressureMb',
 'LastHourMaxAtmosphericPressureMb',
 'LastHourMinAtmosphericPressureMb',
 'HourlyDryBulbAirTemperatureC',
 'DewPointTemperatureC',
 'LastHourMaxTemperatureC',
 'LastHourMinTemperatureC',
 'LastHourMaxDewPointTemperatureC',
 'LastHourMinDewPointTemperatureC',
 'LastHourMaxRelativeHumidityPercentage',
 'LastHourMinRelativeHumidityPercentage',
 'HourlyRelativeHumidityPercentage',
 'HourlyWindDirectionRadiusDegrees',
 'MaximumWindGustMs',
 'HourlyWindSpeedMs',
 'Height']
summary_stats = df_central_west.select(cols_num_2).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                    count                 mean  \
TotalHourlyPrecipitationMm               8888790  0.15587833664646028   
HourlyStationLevelAtmosphericPressureMb  8888790    954.4505846352528   
LastHourMaxAtmosphericPressureMb         8888790    954.7528316452547   
LastHourMinAtmosphericPressureMb         8888790    954.1539553190022   
HourlyDryBulbAirTemperatureC             8888790   24.150351510160405   
DewPointTemperatureC                     8888790    17.05682287465459   
LastHourMaxTemperatureC                  8888790   24.875164414953872   
LastHourMinTemperatureC                  8888790    23.45057701891924   
LastHourMaxDewPointTemperatureC          8888790   17.635270942389038   
LastHourMinDewPointTemperatureC          8888790   16.503919667356143   
LastHourMaxRelativeHumidityPercentage    8888790    71.95631632651913   
LastHourMinRelativeHumidityPercentage    8888790    65.74890868160908   
HourlyRelativeHumidityPercentage         8888790    68.86778774163862   
HourlyWindDirectionRadiusDegrees         8888790   169.39805575337024   
MaximumWindGustMs                        8888790    4.338546573830633   
HourlyWindSpeedMs                        8888790    1.714640530375634   
Height                                   8888790    527.0503490970012   

summary                                              stddev    min    25%  \
TotalHourlyPrecipitationMm               1.3538619632991884    0.0    0.0   
HourlyStationLevelAtmosphericPressureMb  29.181205537167283  855.7  934.6   
LastHourMaxAtmosphericPressureMb         29.197534953225965  865.3  934.9   
LastHourMinAtmosphericPressureMb         29.164794959954367  855.4  934.3   
HourlyDryBulbAirTemperatureC              5.025169092192316   -2.4   21.0   
DewPointTemperatureC                        4.8678836396229  -10.0   14.1   
LastHourMaxTemperatureC                   5.159634604214579   -2.0   21.5   
LastHourMinTemperatureC                   4.874272823640853   -9.5   20.5   
LastHourMaxDewPointTemperatureC           4.809922302073821   -9.1   14.7   
LastHourMinDewPointTemperatureC           4.936963214102215  -10.0   13.5   
LastHourMaxRelativeHumidityPercentage    20.749232317931398      7     58   
LastHourMinRelativeHumidityPercentage     21.91059896743359      7     49   
HourlyRelativeHumidityPercentage          21.45090485128256      7     53   
HourlyWindDirectionRadiusDegrees          106.0929046234159      1     76   
MaximumWindGustMs                        2.8401713686491643    0.0    2.3   
HourlyWindSpeedMs                        1.4855428496317302    0.0    0.4   
Height                                    288.0210018334554    5.0  320.0   

summary                                    50%    75%     max  
TotalHourlyPrecipitationMm                 0.0    0.0    96.0  
HourlyStationLevelAtmosphericPressureMb  960.2  976.1  1028.3  
LastHourMaxAtmosphericPressureMb         960.5  976.4  1029.2  
LastHourMinAtmosphericPressureMb         959.9  975.8  1028.1  
HourlyDryBulbAirTemperatureC              23.7   27.6    44.7  
DewPointTemperatureC                      18.4   20.8    42.7  
LastHourMaxTemperatureC                   24.4   28.6    45.0  
LastHourMinTemperatureC                   23.1   26.6    43.6  
LastHourMaxDewPointTemperatureC           18.9   21.3    43.0  
LastHourMinDewPointTemperatureC           17.8   20.3    38.5  
LastHourMaxRelativeHumidityPercentage       77     90     100  
LastHourMinRelativeHumidityPercentage       69     85     100  
HourlyRelativeHumidityPercentage            73     88     100  
HourlyWindDirectionRadiusDegrees           157    259     360  
MaximumWindGustMs                          4.0    6.1    45.9  
HourlyWindSpeedMs                          1.5    2.6    17.9  
Height                                   469.0  737.0  1264.7

#### Tratamento do North

In [26]:
# Schema, show e count do DataFrame de North

df_north.printSchema()
df_north.show(5, truncate=False) 
df_north.count()

root
 |-- index: integer (nullable = true)
 |-- Data: date (nullable = true)
 |-- Hora: timestamp (nullable = true)
 |-- PRECIPITAÇÃO TOTAL, HORÁRIO (mm): double (nullable = true)
 |-- PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB): double (nullable = true)
 |-- PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- RADIACAO GLOBAL (Kj/m²): integer (nullable = true)
 |-- TEMPERATURA DO AR - BULBO SECO, HORARIA (°C): double (nullable = true)
 |-- TEMPERATURA DO PONTO DE ORVALHO (°C): double (nullable = true)
 |-- TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- UMIDADE REL. MAX. NA HORA ANT. (AUT) (%): integer (nullable = t

8392320

Estes comandos são usados para exibir a estrutura, as primeiras 5 linhas e o total de linhas do dataframe, proporcionando uma visão rápida da estrutura, dos dados iniciais e da quantidade de linhas do dataframe.

In [27]:
# renomear as colunas
df_north = df_north.toDF(*new_column_names)

# corrigir o data type de hora que ao ser importado para o Spark adiciona a data 
df_north = df_north.withColumn("Hour", date_format("Hour", "HH:mm"))

Foram renomeadas as colunas e foi ajustado o tipo de dados da coluna "Hora", removendo a parte da data que foi adicionada durante a importação para o Spark e mantendo apenas o formato de hora no estilo "HH:mm".

In [21]:
cols_to_check = [col for col in df_north.columns if col not in ["Index", "Date", "Hour"]]
df_north_nulls_uniques = compute_nulls_and_uniques(df_north, cols_to_check)

Este chunk de código cria uma lista de colunas `cols_to_check`, excluindo as colunas "Index", "Date" e "Hour", e em seguida, chama a função `compute_nulls_and_uniques` para calcular valores nulos e únicos nas colunas selecionadas.

In [22]:
df_north_nulls_uniques.show(n=30)

+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|             feature|count_nulls|percentage_nulls|count_nans|percentage_nans|count_uniques|  percentage_uniques|
+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|TotalHourlyPrecip...|          0|             0.0|         0|            0.0|          386|4.599443300541448E-5|
|HourlyStationLeve...|          0|             0.0|         0|            0.0|         1489|1.774241211011973E-4|
|LastHourMaxAtmosp...|          0|             0.0|         0|            0.0|         1494|1.780199039121482...|
|LastHourMinAtmosp...|          0|             0.0|         0|            0.0|         1501|1.788539998474796E-4|
| GlobalRadiationKjM2|          0|             0.0|         0|            0.0|        23702|0.002824248837031953|
|HourlyDryBulbAirT...|          0|             0.0|         0|            0.0|          

Exibe as primeiras 30 linhas do dataframe `df_north_nulls_uniques`, fornecendo informações sobre valores nulos e únicos para as colunas selecionadas.

In [23]:
# verificar as instâncias duplicadas
df_north.dropDuplicates().count()

8392320

Uma vez que este valor se manteve igual, não foram encontradas instâncias duplicadas.


In [28]:
# summary stats para verificar outliers
summary_stats = df_north.select(cols_num).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                    count                 mean  \
TotalHourlyPrecipitationMm               8392320  -2368.6857935585504   
HourlyStationLevelAtmosphericPressureMb  8392320  -1091.1952161738323   
LastHourMaxAtmosphericPressureMb         8392320  -1099.6736151624286   
LastHourMinAtmosphericPressureMb         8392320  -1100.1618348204067   
GlobalRadiationKjM2                      8392320   -4753.662215215816   
HourlyDryBulbAirTemperatureC             8392320  -1826.6819741620916   
DewPointTemperatureC                     8392320  -2016.0256888798262   
LastHourMaxTemperatureC                  8392320    -1834.73801164637   
LastHourMinTemperatureC                  8392320  -1835.5571699839807   
LastHourMaxDewPointTemperatureC          8392320  -2024.6788539045183   
LastHourMinDewPointTemperatureC          8392320   -2027.630578266789   
LastHourMaxRelativeHumidityPercentage    8392320  -1971.4030543401586   
LastHourMinRelativeHumidityPercentage    8392320  -1980.9499998808435   
HourlyRelativeHumidityPercentage         8392320  -1972.3191112826967   
HourlyWindDirectionRadiusDegrees         8392320  -2082.3071504661407   
MaximumWindGustMs                        8392320   -2154.195745765343   
HourlyWindSpeedMs                        8392320   -2141.019896595772   
Height                                   8392320  -168.50742364455454   

summary                                              stddev      min    25%  \
TotalHourlyPrecipitationMm                 4251.53525509746  -9999.0    0.0   
HourlyStationLevelAtmosphericPressureMb   4308.732662564336  -9999.0  974.4   
LastHourMaxAtmosphericPressureMb          4315.760881254735  -9999.0  974.5   
LastHourMinAtmosphericPressureMb          4315.489035326974  -9999.0  973.8   
GlobalRadiationKjM2                       5871.869395941868    -9999  -9999   
HourlyDryBulbAirTemperatureC             3891.5006837930287  -9999.0   22.1   
DewPointTemperatureC                      4032.835306610167  -9999.0   14.9   
LastHourMaxTemperatureC                   3898.670436457656  -9999.0   22.4   
LastHourMinTemperatureC                  3898.0808105383735  -9999.0   21.8   
LastHourMaxDewPointTemperatureC          4039.7042577833317  -9999.0   15.5   
LastHourMinDewPointTemperatureC           4040.888398793406  -9999.0   14.1   
LastHourMaxRelativeHumidityPercentage     4057.146118167845    -9999     46   
LastHourMinRelativeHumidityPercentage    4058.8188742876323    -9999     39   
HourlyRelativeHumidityPercentage          4055.220502345159    -9999     42   
HourlyWindDirectionRadiusDegrees          4207.228298389133    -9999     13   
MaximumWindGustMs                         4114.295421558271  -9999.0    0.0   
HourlyWindSpeedMs                         4102.944033870761  -9999.0    0.0   
Height                                    1812.282577165869  -9999.0   55.0   

summary                                    50%     75%     max  
TotalHourlyPrecipitationMm                 0.0     0.0    97.2  
HourlyStationLevelAtmosphericPressureMb  991.5  1004.0  1050.0  
LastHourMaxAtmosphericPressureMb         991.7  1004.3  1049.8  
LastHourMinAtmosphericPressureMb         991.1  1003.7  1050.0  
GlobalRadiationKjM2                      -9999     953   45305  
HourlyDryBulbAirTemperatureC              24.7    28.1    42.2  
DewPointTemperatureC                      21.6    22.9    43.5  
LastHourMaxTemperatureC                   25.1    29.0    45.0  
LastHourMinTemperatureC                   24.3    27.3    45.0  
LastHourMaxDewPointTemperatureC           22.0    23.3    44.4  
LastHourMinDewPointTemperatureC           21.1    22.5    39.8  
LastHourMaxRelativeHumidityPercentage       78      91     100  
LastHourMinRelativeHumidityPercentage       70      88     100  
HourlyRelativeHumidityPercentage            74      90     100  
HourlyWindDirectionRadiusDegrees            89     203     360  
MaximumWindGustMs                          2.2     4.5    99.7  
Hourl

Aqui são calculadas as *summary stats* para as colunas numéricas selecionadas, com o objetivo de verificar a presença de outliers.

In [29]:
# Inicializa uma lista para armazenar os resultados
resultados = []

# Itera sobre todas as colunas e conta as ocorrências de -9999
for coluna in cols_num:
    contagem = df_north.select(spark_sum(when(col(coluna) == -9999, 1).otherwise(0)).alias(coluna)).collect()[0][coluna]
    resultados.append((coluna, contagem))

# Cria um DataFrame a partir dos resultados
resultado_df = spark.createDataFrame(resultados, ["Coluna", "Contagem_de_-9999"])

# Mostra o DataFrame de resultados
resultado_df.show()

+--------------------+-----------------+
|              Coluna|Contagem_de_-9999|
+--------------------+-----------------+
|TotalHourlyPrecip...|          1988221|
|HourlyStationLeve...|          1591222|
|LastHourMaxAtmosp...|          1597892|
|LastHourMinAtmosp...|          1597871|
| GlobalRadiationKjM2|          4540804|
|HourlyDryBulbAirT...|          1551208|
|DewPointTemperatureC|          1706311|
|LastHourMaxTemper...|          1558370|
|LastHourMinTemper...|          1558241|
|LastHourMaxDewPoi...|          1713899|
|LastHourMinDewPoi...|          1715709|
|LastHourMaxRelati...|          1707478|
|LastHourMinRelati...|          1711836|
|HourlyRelativeHum...|          1706495|
|HourlyWindDirecti...|          1847536|
|   MaximumWindGustMs|          1810415|
|   HourlyWindSpeedMs|          1797836|
|              Height|           273960|
+--------------------+-----------------+



Verificámos que havia muitas observações com o valor -9999, que foram usadas sobre os valores omissos. No entanto, para garantir que esses valores não influenciem negativamente a estrutura e o padrão da nossa regressão, decidimos removê-los. No nosso caso, vamos proceder à eliminação da coluna `GlobalRadiation` e, nas outras colunas, vamos eliminar todas as observações que contêm o valor -9999. Esta abordagem assegura que a qualidade dos dados não comprometerá a precisão e a robustez dos nossos modelos preditivos.

In [51]:
# drop da coluna GlobalRadiationKjM2 por ter muitos missings
df_north = df_north.drop("GlobalRadiationKjM2")

In [55]:
# remover linhas com valor -9999 em qualquer coluna
df_north = df_north.filter(~col("TotalHourlyPrecipitationMm").eqNullSafe(-9999) &
                                                  ~col("HourlyStationLevelAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMinAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("HourlyDryBulbAirTemperatureC").eqNullSafe(-9999) &
                                                  ~col("DewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("LastHourMinRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyWindDirectionRadiusDegrees").eqNullSafe(-9999) &
                                                  ~col("MaximumWindGustMs").eqNullSafe(-9999) &
                                                  ~col("HourlyWindSpeedMs").eqNullSafe(-9999) &
                                                  ~col("Height").eqNullSafe(-9999))

In [56]:
df_north.printSchema()
df_north.show()
df_north.count()

root
 |-- Index: integer (nullable = true)
 |-- Date: date (nullable = true)
 |-- Hour: string (nullable = true)
 |-- TotalHourlyPrecipitationMm: double (nullable = true)
 |-- HourlyStationLevelAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMaxAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMinAtmosphericPressureMb: double (nullable = true)
 |-- HourlyDryBulbAirTemperatureC: double (nullable = true)
 |-- DewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxTemperatureC: double (nullable = true)
 |-- LastHourMinTemperatureC: double (nullable = true)
 |-- LastHourMaxDewPointTemperatureC: double (nullable = true)
 |-- LastHourMinDewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxRelativeHumidityPercentage: integer (nullable = true)
 |-- LastHourMinRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyWindDirectionRadiusDegrees: integer (nullable = true)
 |-- Maximum

5864479

O número de instâncias reduziu de 8392320 para 5864479 após a eliminação das observações com o valor -9999.

In [57]:
# summary stats após transformações
summary_stats = df_north.select(cols_num_2).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                    count                 mean  \
TotalHourlyPrecipitationMm               5864479  0.22598713372488285   
HourlyStationLevelAtmosphericPressureMb  5864479     992.990236012442   
LastHourMaxAtmosphericPressureMb         5864479    993.3103363146214   
LastHourMinAtmosphericPressureMb         5864479    992.6755037915613   
HourlyDryBulbAirTemperatureC             5864479   26.416893248317574   
DewPointTemperatureC                     5864479   21.270238055247628   
LastHourMaxTemperatureC                  5864479   27.034341123908888   
LastHourMinTemperatureC                  5864479   25.834302160515904   
LastHourMaxDewPointTemperatureC          5864479   21.784918268101794   
LastHourMinDewPointTemperatureC          5864479   20.786230371018547   
LastHourMaxRelativeHumidityPercentage    5864479    78.97518961189903   
LastHourMinRelativeHumidityPercentage    5864479    73.50939341755678   
HourlyRelativeHumidityPercentage         5864479    76.28801859466118   
HourlyWindDirectionRadiusDegrees         5864479   152.28756433435944   
MaximumWindGustMs                        5864479    3.648461372272319   
HourlyWindSpeedMs                        5864479   1.3014656203900072   
Height                                   5864479    163.6454959511578   

summary                                              stddev    min    25%  \
TotalHourlyPrecipitationMm               1.7118436663346557    0.0    0.0   
HourlyStationLevelAtmosphericPressureMb   17.80273933444465  887.2  985.9   
LastHourMaxAtmosphericPressureMb           17.8098707677178  904.9  986.3   
LastHourMinAtmosphericPressureMb         17.793643229124495  839.5  985.6   
HourlyDryBulbAirTemperatureC             3.6892713228630836    6.0   23.7   
DewPointTemperatureC                      3.236428171335968  -10.0   20.7   
LastHourMaxTemperatureC                   3.884501086326331    6.2   24.1   
LastHourMinTemperatureC                  3.4796716289729606   -5.6   23.4   
LastHourMaxDewPointTemperatureC           3.171992041502342   -9.8   21.2   
LastHourMinDewPointTemperatureC          3.3164380388523367  -10.0   20.2   
LastHourMaxRelativeHumidityPercentage    17.078819746274124      7     70   
LastHourMinRelativeHumidityPercentage    18.985488928785394      7     61   
HourlyRelativeHumidityPercentage         18.133036681278885      7     65   
HourlyWindDirectionRadiusDegrees         103.75979514137387      1     65   
MaximumWindGustMs                        2.6508110764234267    0.0    1.6   
HourlyWindSpeedMs                        1.2372159103619464    0.0    0.3   
Height                                   158.01918955319715   9.92   59.0   

summary                                     50%     75%     max  
TotalHourlyPrecipitationMm                  0.0     0.0    97.2  
HourlyStationLevelAtmosphericPressureMb   997.5  1005.6  1049.2  
LastHourMaxAtmosphericPressureMb          997.9  1005.9  1049.8  
LastHourMinAtmosphericPressureMb          997.2  1005.3  1048.0  
HourlyDryBulbAirTemperatureC               25.7    29.0    42.2  
DewPointTemperatureC                       22.2    23.1    37.2  
LastHourMaxTemperatureC                    26.3    30.0    45.0  
LastHourMinTemperatureC                    25.2    28.1    41.3  
LastHourMaxDewPointTemperatureC            22.6    23.6    39.7  
LastHourMinDewPointTemperatureC            21.8    22.7    33.9  
LastHourMaxRelativeHumidityPercentage        84      92     100  
LastHourMinRelativeHumidityPercentage        78      90     100  
HourlyRelativeHumidityPercentage             81      91     100  
HourlyWindDirectionRadiusDegrees            127     236     360  
MaximumWindGustMs                           3.2     5.3    99.7  
HourlyWindSpeedMs                           1.0     2.0    13.6  
Height                                   111.98   220.0   798.0

### Tratamento do Northeast

In [30]:
# Schema, show e count do DataFrame de Northeast

df_northeast.printSchema()
df_northeast.show(5, truncate=False) 
df_northeast.count()

root
 |-- index: integer (nullable = true)
 |-- Data: date (nullable = true)
 |-- Hora: timestamp (nullable = true)
 |-- PRECIPITAÇÃO TOTAL, HORÁRIO (mm): double (nullable = true)
 |-- PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB): integer (nullable = true)
 |-- PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- RADIACAO GLOBAL (Kj/m²): integer (nullable = true)
 |-- TEMPERATURA DO AR - BULBO SECO, HORARIA (°C): double (nullable = true)
 |-- TEMPERATURA DO PONTO DE ORVALHO (°C): double (nullable = true)
 |-- TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- UMIDADE REL. MAX. NA HORA ANT. (AUT) (%): integer (nullable = 

16260936

Estes comandos são usados para exibir a estrutura, as primeiras 5 linhas e o total de linhas do dataframe, proporcionando uma visão rápida da estrutura, dos dados iniciais e da quantidade de linhas do dataframe.

In [31]:
# renomear as colunas
df_northeast = df_northeast.toDF(*new_column_names)

# corrigir o data type de hora que ao ser importado para o Spark adiciona a data 
df_northeast = df_northeast.withColumn("Hour", date_format("Hour", "HH:mm"))

Foram renomeadas as colunas e foi ajustado o tipo de dados da coluna "Hora", removendo a parte da data que foi adicionada durante a importação para o Spark e mantendo apenas o formato de hora no estilo "HH:mm".

In [27]:
cols_to_check = [col for col in df_northeast.columns if col not in ["Index", "Date", "Hour"]]
df_northeast_nulls_uniques = compute_nulls_and_uniques(df_northeast, cols_to_check)

Este chunk de código cria uma lista de colunas `cols_to_check`, excluindo as colunas "Index", "Date" e "Hour" do dataframe `df_northeast`, e em seguida, chama a função `compute_nulls_and_uniques` para calcular valores nulos e únicos nas colunas selecionadas.

In [28]:
df_northeast_nulls_uniques.show(n=30)

+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|             feature|count_nulls|percentage_nulls|count_nans|percentage_nans|count_uniques|  percentage_uniques|
+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|TotalHourlyPrecip...|          0|             0.0|         0|            0.0|          375| 2.30614031074226E-5|
|HourlyStationLeve...|          0|             0.0|         0|            0.0|          169|1.039300566707845E-5|
|LastHourMaxAtmosp...|          0|             0.0|         0|            0.0|         1605|9.870280529976873E-5|
|LastHourMinAtmosp...|          0|             0.0|         0|            0.0|         1613|9.919478189939374E-5|
| GlobalRadiationKjM2|          0|             0.0|         0|            0.0|        42475|0.002612088258634...|
|HourlyDryBulbAirT...|          0|             0.0|         0|            0.0|          

Exibe as primeiras 30 linhas do dataframe `df_northeast_nulls_uniques`, fornecendo informações sobre valores nulos e únicos para as colunas selecionadas.

In [29]:
# verificar as instâncias duplicadas
df_northeast.dropDuplicates().count()

16260936

Uma vez que este valor se manteve igual, não foram encontradas instâncias duplicadas.

In [32]:
# summary stats para verificar outliers
summary_stats = df_northeast.select(cols_num).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                     count                 mean  \
TotalHourlyPrecipitationMm               16260936   -1566.483971562102   
HourlyStationLevelAtmosphericPressureMb  16260936   -266.7612432027283   
LastHourMaxAtmosphericPressureMb         16260936  -271.93856585499816   
LastHourMinAtmosphericPressureMb         16260936   -272.3187664227925   
GlobalRadiationKjM2                      16260936   -4245.189333381547   
HourlyDryBulbAirTemperatureC             16260936  -1110.7853815487615   
DewPointTemperatureC                     16260936  -1286.8160757474195   
LastHourMaxTemperatureC                  16260936  -1108.9471762080525   
LastHourMinTemperatureC                  16260936  -1108.4590956449206   
LastHourMaxDewPointTemperatureC          16260936  -1283.3920284232072   
LastHourMinDewPointTemperatureC          16260936  -1289.8456291200039   
LastHourMaxRelativeHumidityPercentage    16260936  -1238.6423771054754   
LastHourMinRelativeHumidityPercentage    16260936  -1251.8095034627772   
HourlyRelativeHumidityPercentage         16260936   -1239.523895364941   
HourlyWindDirectionRadiusDegrees         16260936    -1278.79886742067   
MaximumWindGustMs                        16260936  -1348.0234931065397   
HourlyWindSpeedMs                        16260936  -1351.6922905667304   
Height                                   16260936    266.2216892458922   

summary                                              stddev      min    25%  \
TotalHourlyPrecipitationMm               3634.5957641889363  -9999.0    0.0   
HourlyStationLevelAtmosphericPressureMb   3484.407567701511    -9999    956   
LastHourMaxAtmosphericPressureMb          3491.025856150667  -9999.0  956.1   
LastHourMinAtmosphericPressureMb         3490.7173440381625  -9999.0  955.5   
GlobalRadiationKjM2                       6251.677538169608    -9999  -9999   
HourlyDryBulbAirTemperatureC             3178.5290798786423  -9999.0   21.7   
DewPointTemperatureC                     3372.4417909626536  -9999.0   14.4   
LastHourMaxTemperatureC                  3177.1899589644763  -9999.0   22.1   
LastHourMinTemperatureC                   3174.831241616291  -9999.0   21.3   
LastHourMaxDewPointTemperatureC           3369.330955444254  -9999.0   15.1   
LastHourMinDewPointTemperatureC             3375.1233788725  -9999.0   13.8   
LastHourMaxRelativeHumidityPercentage    3387.0833758277963    -9999     45   
LastHourMinRelativeHumidityPercentage    3394.5865835105556    -9999     38   
HourlyRelativeHumidityPercentage         3384.6428991847506    -9999     42   
HourlyWindDirectionRadiusDegrees          3513.850214852869    -9999     56   
MaximumWindGustMs                        3422.0415238130286  -9999.0    2.0   
HourlyWindSpeedMs                        3421.8587153042035  -9999.0    0.4   
Height                                    414.3262507094037  -9999.0   78.0   

summary                                    50%     75%     max  
TotalHourlyPrecipitationMm                 0.0     0.0    97.6  
HourlyStationLevelAtmosphericPressureMb    980    1000    1050  
LastHourMaxAtmosphericPressureMb         979.7  1000.6  1050.0  
LastHourMinAtmosphericPressureMb         979.2  1000.0  1050.0  
GlobalRadiationKjM2                      -9999    1360   51588  
HourlyDryBulbAirTemperatureC              24.8    28.3    45.0  
DewPointTemperatureC                      18.7    21.1    45.0  
LastHourMaxTemperatureC                   25.4    29.1    45.0  
LastHourMinTemperatureC                   24.3    27.5    45.0  
LastHourMaxDewPointTemperatureC           19.2    21.6    45.0  
LastHourMinDewPointTemperatureC           18.2    20.7    45.0  
LastHourMaxRelativeHumidityPercentage       71      86     100  
LastHourMinRelativeHumidityPercentage       63      81     100  
HourlyRelativeHumidityPercentage            67      84     100  
HourlyWindDirectionRadiusDegrees           109     156     360  
MaximumWindGustMs                          4.8     

Aqui são calculadas as *summary stats* para as colunas numéricas, com o objetivo de verificar a presença de outliers.


In [33]:
# Inicializa uma lista para armazenar os resultados
resultados = []

# Itera sobre todas as colunas e conta as ocorrências de -9999
for coluna in cols_num:
    contagem = df_northeast.select(spark_sum(when(col(coluna) == -9999, 1).otherwise(0)).alias(coluna)).collect()[0][coluna]
    resultados.append((coluna, contagem))

# Cria um DataFrame a partir dos resultados
resultado_df = spark.createDataFrame(resultados, ["Coluna", "Contagem_de_-9999"])

# Mostra o DataFrame de resultados
resultado_df.show()

+--------------------+-----------------+
|              Coluna|Contagem_de_-9999|
+--------------------+-----------------+
|TotalHourlyPrecip...|          2547648|
|HourlyStationLeve...|          1847478|
|LastHourMaxAtmosp...|          1855451|
|LastHourMinAtmosp...|          1855289|
| GlobalRadiationKjM2|          8305221|
|HourlyDryBulbAirT...|          1843754|
|DewPointTemperatureC|          2119052|
|LastHourMaxTemper...|          1841701|
|LastHourMinTemper...|          1839098|
|LastHourMaxDewPoi...|          2114207|
|LastHourMinDewPoi...|          2123267|
|LastHourMaxRelati...|          2114644|
|LastHourMinRelati...|          2128352|
|HourlyRelativeHum...|          2112360|
|HourlyWindDirecti...|          2270606|
|   MaximumWindGustMs|          2200138|
|   HourlyWindSpeedMs|          2201550|
|              Height|            18264|
+--------------------+-----------------+



Verificámos que havia muitas observações com o valor -9999, que foram usadas sobre os valores omissos. No entanto, para garantir que esses valores não influenciem negativamente a estrutura e o padrão da nossa regressão, decidimos removê-los. No nosso caso, vamos proceder à eliminação da coluna `GlobalRadiation` e, nas outras colunas, vamos eliminar todas as observações que contêm o valor -9999. Esta abordagem assegura que a qualidade dos dados não comprometerá a precisão e a robustez dos nossos modelos preditivos.

In [58]:
# drop da coluna GlobalRadiationKjM2 por ter muitos missings
df_northeast = df_northeast.drop("GlobalRadiationKjM2")

In [59]:
# remover linhas com valor -9999 em qualquer coluna
df_northeast = df_northeast.filter(~col("TotalHourlyPrecipitationMm").eqNullSafe(-9999) &
                                                  ~col("HourlyStationLevelAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMinAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("HourlyDryBulbAirTemperatureC").eqNullSafe(-9999) &
                                                  ~col("DewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("LastHourMinRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyWindDirectionRadiusDegrees").eqNullSafe(-9999) &
                                                  ~col("MaximumWindGustMs").eqNullSafe(-9999) &
                                                  ~col("HourlyWindSpeedMs").eqNullSafe(-9999) &
                                                  ~col("Height").eqNullSafe(-9999))

In [60]:
df_northeast.printSchema()
df_northeast.show()
df_northeast.count()

root
 |-- Index: integer (nullable = true)
 |-- Date: date (nullable = true)
 |-- Hour: string (nullable = true)
 |-- TotalHourlyPrecipitationMm: double (nullable = true)
 |-- HourlyStationLevelAtmosphericPressureMb: integer (nullable = true)
 |-- LastHourMaxAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMinAtmosphericPressureMb: double (nullable = true)
 |-- HourlyDryBulbAirTemperatureC: double (nullable = true)
 |-- DewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxTemperatureC: double (nullable = true)
 |-- LastHourMinTemperatureC: double (nullable = true)
 |-- LastHourMaxDewPointTemperatureC: double (nullable = true)
 |-- LastHourMinDewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxRelativeHumidityPercentage: integer (nullable = true)
 |-- LastHourMinRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyWindDirectionRadiusDegrees: integer (nullable = true)
 |-- Maximu

12934432

O número de instâncias reduziu de 16260936 para 12934432 após a eliminação das observações com o valor -9999.

In [61]:
# summary stats após transformações
summary_stats = df_northeast.select(cols_num_2).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                     count                 mean  \
TotalHourlyPrecipitationMm               12934432  0.10069547700275833   
HourlyStationLevelAtmosphericPressureMb  12934432    979.8653690397847   
LastHourMaxAtmosphericPressureMb         12934432    980.0964460905658   
LastHourMinAtmosphericPressureMb         12934432    979.5417305375341   
HourlyDryBulbAirTemperatureC             12934432   25.912948059875884   
DewPointTemperatureC                     12934432   18.552767558714606   
LastHourMaxTemperatureC                  12934432   26.566760364892566   
LastHourMinTemperatureC                  12934432   25.295624523751734   
LastHourMaxDewPointTemperatureC          12934432   19.067260131716587   
LastHourMinDewPointTemperatureC          12934432    18.05691530946243   
LastHourMaxRelativeHumidityPercentage    12934432    70.62403946303942   
LastHourMinRelativeHumidityPercentage    12934432    65.18928971910015   
HourlyRelativeHumidityPercentage         12934432    67.93432189368656   
HourlyWindDirectionRadiusDegrees         12934432   135.35653115652855   
MaximumWindGustMs                        12934432    5.694832946664153   
HourlyWindSpeedMs                        12934432    2.419172322371967   
Height                                   12934432    292.7568217837894   

summary                                              stddev    min    25%  \
TotalHourlyPrecipitationMm               0.9943471991509556    0.0    0.0   
HourlyStationLevelAtmosphericPressureMb  26.114924718914704    865    965   
LastHourMaxAtmosphericPressureMb          26.11880519769385  864.6  964.8   
LastHourMinAtmosphericPressureMb         26.108905719377745  864.5  964.2   
HourlyDryBulbAirTemperatureC              4.287781801370853    0.2   22.9   
DewPointTemperatureC                     3.7949416410255483  -10.0   16.5   
LastHourMaxTemperatureC                  4.4587584206909465    8.7   23.4   
LastHourMinTemperatureC                   4.107442798547635   -0.2   22.5   
LastHourMaxDewPointTemperatureC          3.7218634155189947   -9.8   17.0   
LastHourMinDewPointTemperatureC          3.8800745135948405  -10.0   15.9   
LastHourMaxRelativeHumidityPercentage     20.23444032430476      8     57   
LastHourMinRelativeHumidityPercentage     21.25292142774993      7     49   
HourlyRelativeHumidityPercentage          20.83353459073767      7     53   
HourlyWindDirectionRadiusDegrees          80.15385393221626      1     83   
MaximumWindGustMs                         3.066790742750164    0.0    3.2   
HourlyWindSpeedMs                        1.7183446743089532    0.0    1.1   
Height                                   234.50881244864965    0.1   85.0   

summary                                     50%     75%     max  
TotalHourlyPrecipitationMm                  0.0     0.0    97.6  
HourlyStationLevelAtmosphericPressureMb     983    1002    1050  
LastHourMaxAtmosphericPressureMb          983.4  1002.2  1050.0  
LastHourMinAtmosphericPressureMb          982.8  1001.6  1049.6  
HourlyDryBulbAirTemperatureC               25.5    28.8    45.0  
DewPointTemperatureC                       19.3    21.3    44.7  
LastHourMaxTemperatureC                    26.2    29.7    45.0  
LastHourMinTemperatureC                    25.0    28.0    44.9  
LastHourMaxDewPointTemperatureC            19.8    21.8    44.7  
LastHourMinDewPointTemperatureC            18.8    20.9    44.6  
LastHourMaxRelativeHumidityPercentage        75      88     100  
LastHourMinRelativeHumidityPercentage        68      83     100  
HourlyRelativeHumidityPercentage             71      86     100  
HourlyWindDirectionRadiusDegrees            120     166     360  
MaximumWindGustMs                           5.6     7.9    47.3  
HourlyWindSpeedMs                           2.2     3.6    17.7  
Height                                   249.89   430.0  1290.0

### Tratamento de South

In [34]:
# Schema, show e count do DataFrame de South

df_south.printSchema()
df_south.show(5, truncate=False) 
df_south.count()

root
 |-- index: integer (nullable = true)
 |-- Data: date (nullable = true)
 |-- Hora: timestamp (nullable = true)
 |-- PRECIPITAÇÃO TOTAL, HORÁRIO (mm): double (nullable = true)
 |-- PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB): double (nullable = true)
 |-- PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- RADIACAO GLOBAL (Kj/m²): integer (nullable = true)
 |-- TEMPERATURA DO AR - BULBO SECO, HORARIA (°C): double (nullable = true)
 |-- TEMPERATURA DO PONTO DE ORVALHO (°C): double (nullable = true)
 |-- TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- UMIDADE REL. MAX. NA HORA ANT. (AUT) (%): integer (nullable = t

10284888

Estes comandos são usados para exibir a estrutura, as primeiras 5 linhas e o total de linhas do dataframe, proporcionando uma visão rápida da estrutura, dos dados iniciais e da quantidade de linhas do dataframe.

In [35]:
# renomear as colunas
df_south = df_south.toDF(*new_column_names)

# corrigir o data type de hora que ao ser importado para o Spark adiciona a data 
df_south = df_south.withColumn("Hour", date_format("Hour", "HH:mm"))

Foram renomeadas as colunas e foi ajustado o tipo de dados da coluna "Hora", removendo a parte da data que foi adicionada durante a importação para o Spark e mantendo apenas o formato de hora no estilo "HH:mm".

In [33]:
cols_to_check = [col for col in df_south.columns if col not in ["Index", "Date", "Hour"]]
df_south_nulls_uniques = compute_nulls_and_uniques(df_south, cols_to_check)

Este chunk de código cria uma lista de colunas `cols_to_check`, excluindo as colunas "Index", "Date" e "Hour", e em seguida, chama a função `compute_nulls_and_uniques` para calcular valores nulos e únicos nas colunas selecionadas.

In [34]:
df_south_nulls_uniques.show(n=30)

+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|             feature|count_nulls|percentage_nulls|count_nans|percentage_nans|count_uniques|  percentage_uniques|
+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|TotalHourlyPrecip...|          0|             0.0|         0|            0.0|          332|3.228037096757884E-5|
|HourlyStationLeve...|          0|             0.0|         0|            0.0|         2249|2.186703442954361...|
|LastHourMaxAtmosp...|          0|             0.0|         0|            0.0|         2275|2.211983251543429...|
|LastHourMinAtmosp...|          0|             0.0|         0|            0.0|         2269|2.206149449561336...|
| GlobalRadiationKjM2|          0|             0.0|         0|            0.0|         5434|5.283479995115163E-4|
|HourlyDryBulbAirT...|          0|             0.0|         0|            0.0|          

Exibe as primeiras 30 linhas do dataframe `df_south_nulls_uniques`, fornecendo informações sobre valores nulos e únicos para as colunas selecionadas.

In [35]:
# verificar as instâncias duplicadas
df_south.dropDuplicates().count()

10284888

Uma vez que este valor se manteve igual, não foram encontradas instâncias duplicadas.

In [36]:
# summary stats para verificar outliers
summary_stats = df_south.select(cols_num).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                     count                 mean  \
TotalHourlyPrecipitationMm               10284888  -1003.1757941943387   
HourlyStationLevelAtmosphericPressureMb  10284888   136.11775491380934   
LastHourMaxAtmosphericPressureMb         10284888   131.34381513925746   
LastHourMinAtmosphericPressureMb         10284888   130.85825540346087   
GlobalRadiationKjM2                      10284888   -4277.233784947391   
HourlyDryBulbAirTemperatureC             10284888    -741.401004707103   
DewPointTemperatureC                     10284888   -922.4772457901425   
LastHourMaxTemperatureC                  10284888   -742.3154842814149   
LastHourMinTemperatureC                  10284888   -743.5768328833522   
LastHourMaxDewPointTemperatureC          10284888   -923.1730407856725   
LastHourMinDewPointTemperatureC          10284888   -932.2648713724454   
LastHourMaxRelativeHumidityPercentage    10284888   -864.2358404875191   
LastHourMinRelativeHumidityPercentage    10284888   -886.9975814029283   
HourlyRelativeHumidityPercentage         10284888   -875.5060697792723   
HourlyWindDirectionRadiusDegrees         10284888   -811.3361787702501   
MaximumWindGustMs                        10284888   -936.5487959907827   
HourlyWindSpeedMs                        10284888    -934.966421335807   
Height                                   10284888    481.0038268575586   

summary                                              stddev      min    25%  \
TotalHourlyPrecipitationMm               3004.3491131084174  -9999.0    0.0   
HourlyStationLevelAtmosphericPressureMb  2891.0813475500845  -9999.0  918.2   
LastHourMaxAtmosphericPressureMb          2899.225736685094  -9999.0  918.4   
LastHourMinAtmosphericPressureMb         2899.0481747071203  -9999.0  917.9   
GlobalRadiationKjM2                       5682.026341777482    -9999  -9999   
HourlyDryBulbAirTemperatureC             2653.1419806747035  -9999.0   13.9   
DewPointTemperatureC                     2915.8609065891997  -9999.0    9.7   
LastHourMaxTemperatureC                    2655.65014467017  -9999.0   14.3   
LastHourMinTemperatureC                  2655.6239937520822  -9999.0   13.4   
LastHourMaxDewPointTemperatureC          2917.6644579252397  -9999.0   10.3   
LastHourMinDewPointTemperatureC          2928.6785057800817  -9999.0    9.1   
LastHourMaxRelativeHumidityPercentage    2936.1094102614234    -9999     63   
LastHourMinRelativeHumidityPercentage    2959.5090868946527    -9999     54   
HourlyRelativeHumidityPercentage         2947.8588057858533    -9999     59   
HourlyWindDirectionRadiusDegrees          2987.718337301707    -9999     56   
MaximumWindGustMs                         2921.979744988545  -9999.0    2.4   
HourlyWindSpeedMs                         2915.034388250883  -9999.0    0.4   
Height                                    395.1045607612854      1.0   95.0   

summary                                     50%     75%     max  
TotalHourlyPrecipitationMm                  0.0     0.0    94.4  
HourlyStationLevelAtmosphericPressureMb   958.5  1001.2  1049.9  
LastHourMaxAtmosphericPressureMb          958.7  1001.5  1049.9  
LastHourMinAtmosphericPressureMb          958.2  1000.9  1049.5  
GlobalRadiationKjM2                           0    1014    8259  
HourlyDryBulbAirTemperatureC               18.5    22.6    44.4  
DewPointTemperatureC                       14.2    17.6    43.5  
LastHourMaxTemperatureC                    19.0    23.2    44.7  
LastHourMinTemperatureC                    18.0    21.9    44.9  
LastHourMaxDewPointTemperatureC            14.7    18.1    43.5  
LastHourMinDewPointTemperatureC            13.7    17.2    43.3  
LastHourMaxRelativeHumidityPercentage        81      93     100  
LastHourMinRelativeHumidityPercentage        75      89     100  
HourlyRelativeHumidityPercentage             78      91     100  
HourlyWindDirectionRadiusDegrees            122     232     360  
MaximumWindGustMs                  

Aqui são calculadas as *summary stats* para as colunas numéricas, com o objetivo de verificar a presença de outliers.


In [37]:
# Inicializa uma lista para armazenar os resultados
resultados = []

# Itera sobre todas as colunas e conta as ocorrências de -9999
for coluna in cols_num:
    contagem = df_south.select(spark_sum(when(col(coluna) == -9999, 1).otherwise(0)).alias(coluna)).collect()[0][coluna]
    resultados.append((coluna, contagem))

# Cria um DataFrame a partir dos resultados
resultado_df = spark.createDataFrame(resultados, ["Coluna", "Contagem_de_-9999"])

# Mostra o DataFrame de resultados
resultado_df.show()

+--------------------+-----------------+
|              Coluna|Contagem_de_-9999|
+--------------------+-----------------+
|TotalHourlyPrecip...|          1032035|
|HourlyStationLeve...|           773754|
|LastHourMaxAtmosp...|           778468|
|LastHourMinAtmosp...|           778449|
| GlobalRadiationKjM2|          5055598|
|HourlyDryBulbAirT...|           780622|
|DewPointTemperatureC|           962138|
|LastHourMaxTemper...|           782129|
|LastHourMinTemper...|           782312|
|LastHourMaxDewPoi...|           963351|
|LastHourMinDewPoi...|           971713|
|LastHourMaxRelati...|           963029|
|LastHourMinRelati...|           981391|
|HourlyRelativeHum...|           972192|
|HourlyWindDirecti...|           982663|
|   MaximumWindGustMs|           968521|
|   HourlyWindSpeedMs|           964049|
|              Height|                0|
+--------------------+-----------------+



Verificámos que havia muitas observações com o valor -9999, que foram usadas sobre os valores omissos. No entanto, para garantir que esses valores não influenciem negativamente a estrutura e o padrão da nossa regressão, decidimos removê-los. No nosso caso, vamos proceder à eliminação da coluna `GlobalRadiation` e, nas outras colunas, vamos eliminar todas as observações que contêm o valor -9999. Esta abordagem assegura que a qualidade dos dados não comprometerá a precisão e a robustez dos nossos modelos preditivos.

In [62]:
# drop da coluna GlobalRadiationKjM2 por ter muitos missings
df_south = df_south.drop("GlobalRadiationKjM2")

In [63]:
# remover linhas com valor -9999 em qualquer coluna
df_south = df_south.filter(~col("TotalHourlyPrecipitationMm").eqNullSafe(-9999) &
                                                  ~col("HourlyStationLevelAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMinAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("HourlyDryBulbAirTemperatureC").eqNullSafe(-9999) &
                                                  ~col("DewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("LastHourMinRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyWindDirectionRadiusDegrees").eqNullSafe(-9999) &
                                                  ~col("MaximumWindGustMs").eqNullSafe(-9999) &
                                                  ~col("HourlyWindSpeedMs").eqNullSafe(-9999))

In [64]:
df_south.printSchema()
df_south.show()
df_south.count()

root
 |-- Index: integer (nullable = true)
 |-- Date: date (nullable = true)
 |-- Hour: string (nullable = true)
 |-- TotalHourlyPrecipitationMm: double (nullable = true)
 |-- HourlyStationLevelAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMaxAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMinAtmosphericPressureMb: double (nullable = true)
 |-- HourlyDryBulbAirTemperatureC: double (nullable = true)
 |-- DewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxTemperatureC: double (nullable = true)
 |-- LastHourMinTemperatureC: double (nullable = true)
 |-- LastHourMaxDewPointTemperatureC: double (nullable = true)
 |-- LastHourMinDewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxRelativeHumidityPercentage: integer (nullable = true)
 |-- LastHourMinRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyWindDirectionRadiusDegrees: integer (nullable = true)
 |-- Maximum

8796918

O número de instâncias reduziu de 10284888 para 8796918 após a eliminação das observações com o valor -9999.

In [65]:
# summary stats após transformações
summary_stats = df_south.select(cols_num_2).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                    count                 mean  \
TotalHourlyPrecipitationMm               8796918  0.18660276246743634   
HourlyStationLevelAtmosphericPressureMb  8796918    961.0452742540124   
LastHourMaxAtmosphericPressureMb         8796918    961.3195431286294   
LastHourMinAtmosphericPressureMb         8796918    960.7721982176078   
HourlyDryBulbAirTemperatureC             8796918   19.027324638015177   
DewPointTemperatureC                     8796918    14.31168588817134   
LastHourMaxTemperatureC                  8796918   19.632101788376204   
LastHourMinTemperatureC                  8796918    18.45229506515794   
LastHourMaxDewPointTemperatureC          8796918    14.85478681283606   
LastHourMinDewPointTemperatureC          8796918   13.796836767149498   
LastHourMaxRelativeHumidityPercentage    8796918    79.49205233014563   
LastHourMinRelativeHumidityPercentage    8796918    74.07764639843181   
HourlyRelativeHumidityPercentage         8796918    76.83653013475856   
HourlyWindDirectionRadiusDegrees         8796918   158.86019001200194   
MaximumWindGustMs                        8796918    5.567176413375106   
HourlyWindSpeedMs                        8796918    2.510337245385324   
Height                                   8796918    479.0134039342692   

summary                                              stddev    min    25%  \
TotalHourlyPrecipitationMm                1.247617554987454    0.0    0.0   
HourlyStationLevelAtmosphericPressureMb   42.82285323426238  803.9  926.7   
LastHourMaxAtmosphericPressureMb           42.8362673886135  804.5  926.9   
LastHourMinAtmosphericPressureMb         42.810302553026176  803.1  926.4   
HourlyDryBulbAirTemperatureC              5.932462471913904   -7.7   15.2   
DewPointTemperatureC                      4.972600679615887  -27.5   11.3   
LastHourMaxTemperatureC                   6.046407248221974   -7.6   15.7   
LastHourMinTemperatureC                    5.81633607203578   -7.8   14.8   
LastHourMaxDewPointTemperatureC           4.922473779220011  -25.1   11.9   
LastHourMinDewPointTemperatureC           5.049267278314168  -29.8   10.8   
LastHourMaxRelativeHumidityPercentage    16.583146157761803      7     69   
LastHourMinRelativeHumidityPercentage     18.78439543417671      7     61   
HourlyRelativeHumidityPercentage          17.78138517839171      7     65   
HourlyWindDirectionRadiusDegrees         101.07292772110407      1     75   
MaximumWindGustMs                        3.3938524661357397    0.0    3.2   
HourlyWindSpeedMs                         2.087631686444246    0.0    1.0   
Height                                    386.6320728724842    1.0   95.0   

summary                                    50%     75%     max  
TotalHourlyPrecipitationMm                 0.0     0.0    94.4  
HourlyStationLevelAtmosphericPressureMb  963.4  1002.5  1049.9  
LastHourMaxAtmosphericPressureMb         963.7  1002.8  1049.9  
LastHourMinAtmosphericPressureMb         963.1  1002.2  1048.0  
HourlyDryBulbAirTemperatureC              19.2    23.0    44.2  
DewPointTemperatureC                      14.9    18.0    38.1  
LastHourMaxTemperatureC                   19.7    23.7    44.7  
LastHourMinTemperatureC                   18.7    22.3    41.5  
LastHourMaxDewPointTemperatureC           15.4    18.5    38.1  
LastHourMinDewPointTemperatureC           14.4    17.5    31.7  
LastHourMaxRelativeHumidityPercentage       84      93     100  
LastHourMinRelativeHumidityPercentage       78      90     100  
HourlyRelativeHumidityPercentage            81      92     100  
HourlyWindDirectionRadiusDegrees           137     237     360  
MaximumWindGustMs                          5.3     7.5    49.8  
HourlyWindSpeedMs                          2.2     3.6    29.5  
Height                                   456.0   788.0  1810.0

### Tratamento de Southeast

In [37]:
# Schema, show e count do DataFrame de Southeast

df_southeast.printSchema()
df_southeast.show(5, truncate=False) 
df_southeast.count()

root
 |-- index: integer (nullable = true)
 |-- Data: date (nullable = true)
 |-- Hora: timestamp (nullable = true)
 |-- PRECIPITAÇÃO TOTAL, HORÁRIO (mm): double (nullable = true)
 |-- PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB): double (nullable = true)
 |-- PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB): double (nullable = true)
 |-- RADIACAO GLOBAL (Kj/m²): integer (nullable = true)
 |-- TEMPERATURA DO AR - BULBO SECO, HORARIA (°C): double (nullable = true)
 |-- TEMPERATURA DO PONTO DE ORVALHO (°C): double (nullable = true)
 |-- TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C): double (nullable = true)
 |-- UMIDADE REL. MAX. NA HORA ANT. (AUT) (%): integer (nullable = t

15345216

Estes comandos são usados para exibir a estrutura, as primeiras 5 linhas e o total de linhas do dataframe, proporcionando uma visão rápida da estrutura, dos dados iniciais e da quantidade de linhas do dataframe.

In [38]:
# renomear as colunas
df_southeast = df_southeast.toDF(*new_column_names)

# corrigir o data type de hora que ao ser importado para o Spark adiciona a data 
df_southeast = df_southeast.withColumn("Hour", date_format("Hour", "HH:mm"))

Foram renomeadas as colunas e foi ajustado o tipo de dados da coluna "Hora", removendo a parte da data que foi adicionada durante a importação para o Spark e mantendo apenas o formato de hora no estilo "HH:mm".

In [39]:
cols_to_check = [col for col in df_southeast.columns if col not in ["Index", "Date", "Hour"]]
df_southeast_nulls_uniques = compute_nulls_and_uniques(df_southeast, cols_to_check)


Este chunk de código cria uma lista de colunas `cols_to_check`, excluindo as colunas "Index", "Date" e "Hour", e em seguida, chama a função `compute_nulls_and_uniques` para calcular valores nulos e únicos nas colunas selecionadas.


In [40]:
df_southeast_nulls_uniques.show(n=30)

+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|             feature|count_nulls|percentage_nulls|count_nans|percentage_nans|count_uniques|  percentage_uniques|
+--------------------+-----------+----------------+----------+---------------+-------------+--------------------+
|TotalHourlyPrecip...|          0|             0.0|         0|            0.0|          386|2.515441946206557...|
|HourlyStationLeve...|          0|             0.0|         0|            0.0|         3251|2.118575587336144...|
|LastHourMaxAtmosp...|          0|             0.0|         0|            0.0|         3248|2.116620580642201...|
|LastHourMinAtmosp...|          0|             0.0|         0|            0.0|         3236|2.108800553866429...|
| GlobalRadiationKjM2|          0|             0.0|         0|            0.0|        33430|0.002178529125950394|
|HourlyDryBulbAirT...|          0|             0.0|         0|            0.0|          


Exibe as primeiras 30 linhas do dataframe `df_southeast_uniques`, fornecendo informações sobre valores nulos e únicos para as colunas selecionadas.


In [41]:
df_southeast.dropDuplicates().count()

15345216


Uma vez que este valor se manteve igual, não foram encontradas instâncias duplicadas.


In [42]:
# summary stats para verificar outliers
summary_stats = df_southeast.select(cols_num).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                     count                 mean  \
TotalHourlyPrecipitationMm               15345216   -862.9100386074799   
HourlyStationLevelAtmosphericPressureMb  15345216   153.35224378073508   
LastHourMaxAtmosphericPressureMb         15345216    147.8214425264539   
LastHourMinAtmosphericPressureMb         15345216   147.38702663422904   
GlobalRadiationKjM2                      15345216  -3847.6454573855463   
HourlyDryBulbAirTemperatureC             15345216   -651.4797423900707   
DewPointTemperatureC                     15345216   -778.0925969761441   
LastHourMaxTemperatureC                  15345216   -655.5416456894435   
LastHourMinTemperatureC                  15345216   -656.7468354045982   
LastHourMaxDewPointTemperatureC          15345216   -783.0376560160536   
LastHourMinDewPointTemperatureC          15345216   -791.8674592394109   
LastHourMaxRelativeHumidityPercentage    15345216   -706.1575281182096   
LastHourMinRelativeHumidityPercentage    15345216     -719.18955021552   
HourlyRelativeHumidityPercentage         15345216   -708.3654361724201   
HourlyWindDirectionRadiusDegrees         15345216   -791.1683185821562   
MaximumWindGustMs                        15345216   -911.5658778280044   
HourlyWindSpeedMs                        15345216   -902.4921235255821   
Height                                   15345216     580.958144432645   

summary                                              stddev      min    25%  \
TotalHourlyPrecipitationMm                2808.022521392235  -9999.0    0.0   
HourlyStationLevelAtmosphericPressureMb   2841.400819412801  -9999.0  911.7   
LastHourMaxAtmosphericPressureMb          2850.938764422795  -9999.0  911.9   
LastHourMinAtmosphericPressureMb         2850.7293383761826  -9999.0  911.4   
GlobalRadiationKjM2                       5917.597607164481    -9999  -9999   
HourlyDryBulbAirTemperatureC              2509.008008323635  -9999.0   17.8   
DewPointTemperatureC                      2705.903320766113  -9999.0   12.1   
LastHourMaxTemperatureC                  2517.2881262770165  -9999.0   18.3   
LastHourMinTemperatureC                  2516.8849129417736  -9999.0   17.3   
LastHourMaxDewPointTemperatureC           2714.538036114629  -9999.0   12.7   
LastHourMinDewPointTemperatureC           2726.331928935502  -9999.0   11.6   
LastHourMaxRelativeHumidityPercentage    2694.5629367836145    -9999     57   
LastHourMinRelativeHumidityPercentage    2704.9143256511184    -9999     49   
HourlyRelativeHumidityPercentage          2693.056290903369    -9999     53   
HourlyWindDirectionRadiusDegrees          2953.733583569858    -9999     55   
MaximumWindGustMs                        2885.6018412289022  -9999.0    2.0   
HourlyWindSpeedMs                        2868.2940008498763  -9999.0    0.4   
Height                                    541.0442346975198  -9999.0  297.0   

summary                                    50%    75%     max  
TotalHourlyPrecipitationMm                 0.0    0.0   100.0  
HourlyStationLevelAtmosphericPressureMb  944.0  971.9  1050.0  
LastHourMaxAtmosphericPressureMb         944.2  972.1  1050.0  
LastHourMinAtmosphericPressureMb         943.7  971.5  1050.0  
GlobalRadiationKjM2                          1   1245   51279  
HourlyDryBulbAirTemperatureC              21.5   25.0    44.9  
DewPointTemperatureC                      16.2   18.9    42.7  
LastHourMaxTemperatureC                   22.0   25.9    45.0  
LastHourMinTemperatureC                   20.9   24.3    45.0  
LastHourMaxDewPointTemperatureC           16.7   19.5    44.8  
LastHourMinDewPointTemperatureC           15.7   18.5    44.9  
LastHourMaxRelativeHumidityPercentage       77     90     100  
LastHourMinRelativeHumidityPercentage       70     86     100  
HourlyRelativeHumidityPercentage            74     88     100  
HourlyWindDirectionRadiusDegrees           117    223     360  
MaximumWindGustMs                          4.0    6.2    50.0  
Hou


Aqui são calculadas as *summary stats* para as colunas numéricas, com o objetivo de verificar a presença de outliers.


In [39]:
# Inicializa uma lista para armazenar os resultados
resultados = []

# Itera sobre todas as colunas e conta as ocorrências de -9999
for coluna in cols_num:
    contagem = df_southeast.select(spark_sum(when(col(coluna) == -9999, 1).otherwise(0)).alias(coluna)).collect()[0][coluna]
    resultados.append((coluna, contagem))

# Cria um DataFrame a partir dos resultados
resultado_df = spark.createDataFrame(resultados, ["Coluna", "Contagem_de_-9999"])

# Mostra o DataFrame de resultados
resultado_df.show()

+--------------------+-----------------+
|              Coluna|Contagem_de_-9999|
+--------------------+-----------------+
|TotalHourlyPrecip...|          1324496|
|HourlyStationLeve...|          1114464|
|LastHourMaxAtmosp...|          1122546|
|LastHourMinAtmosp...|          1122482|
| GlobalRadiationKjM2|          7083207|
|HourlyDryBulbAirT...|          1031262|
|DewPointTemperatureC|          1216672|
|LastHourMaxTemper...|          1038460|
|LastHourMinTemper...|          1038400|
|LastHourMaxDewPoi...|          1225038|
|LastHourMinDewPoi...|          1237026|
|LastHourMaxRelati...|          1190074|
|LastHourMinRelati...|          1201616|
|HourlyRelativeHum...|          1189363|
|HourlyWindDirecti...|          1430352|
|   MaximumWindGustMs|          1405538|
|   HourlyWindSpeedMs|          1387730|
|              Height|            18264|
+--------------------+-----------------+




Verificámos que havia muitas observações com o valor -9999, que foram usadas sobre os valores omissos. No entanto, para garantir que esses valores não influenciem negativamente a estrutura e o padrão da nossa regressão, decidimos removê-los. No nosso caso, vamos proceder à eliminação da coluna `GlobalRadiation` e, nas outras colunas, vamos eliminar todas as observações que contêm o valor -9999. Esta abordagem assegura que a qualidade dos dados não comprometerá a precisão e a robustez dos nossos modelos preditivos.


In [66]:
# drop da coluna GlobalRadiationKjM2 por ter muitos missings
df_southeast = df_southeast.drop("GlobalRadiationKjM2")

In [67]:
# remover linhas com valor -9999 em qualquer coluna
df_southeast = df_southeast.filter(~col("TotalHourlyPrecipitationMm").eqNullSafe(-9999) &
                                                  ~col("HourlyStationLevelAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("LastHourMinAtmosphericPressureMb").eqNullSafe(-9999) &
                                                  ~col("HourlyDryBulbAirTemperatureC").eqNullSafe(-9999) &
                                                  ~col("DewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMinDewPointTemperatureC").eqNullSafe(-9999) &
                                                  ~col("LastHourMaxRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("LastHourMinRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyRelativeHumidityPercentage").eqNullSafe(-9999) &
                                                  ~col("HourlyWindDirectionRadiusDegrees").eqNullSafe(-9999) &
                                                  ~col("MaximumWindGustMs").eqNullSafe(-9999) &
                                                  ~col("HourlyWindSpeedMs").eqNullSafe(-9999) &
                                                  ~col("Height").eqNullSafe(-9999))

In [68]:
df_southeast.printSchema()
df_southeast.show()
df_southeast.count()

root
 |-- Index: integer (nullable = true)
 |-- Date: date (nullable = true)
 |-- Hour: string (nullable = true)
 |-- TotalHourlyPrecipitationMm: double (nullable = true)
 |-- HourlyStationLevelAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMaxAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMinAtmosphericPressureMb: double (nullable = true)
 |-- HourlyDryBulbAirTemperatureC: double (nullable = true)
 |-- DewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxTemperatureC: double (nullable = true)
 |-- LastHourMinTemperatureC: double (nullable = true)
 |-- LastHourMaxDewPointTemperatureC: double (nullable = true)
 |-- LastHourMinDewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxRelativeHumidityPercentage: integer (nullable = true)
 |-- LastHourMinRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyWindDirectionRadiusDegrees: integer (nullable = true)
 |-- Maximum

13274895


O número de instâncias reduziu de 15345216 para 13274895 após a eliminação das observações com o valor -9999.

In [69]:
# summary stats após transformações
summary_stats = df_southeast.select(cols_num_2).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                     count                mean  \
TotalHourlyPrecipitationMm               13274895   0.146647623201494   
HourlyStationLevelAtmosphericPressureMb  13274895   948.9438967238514   
LastHourMaxAtmosphericPressureMb         13274895   949.2043552886902   
LastHourMinAtmosphericPressureMb         13274895   948.6860503981273   
HourlyDryBulbAirTemperatureC             13274895   22.06339189123537   
DewPointTemperatureC                     13274895  16.010340119450998   
LastHourMaxTemperatureC                  13274895  22.752046023716147   
LastHourMinTemperatureC                  13274895   21.41178068828419   
LastHourMaxDewPointTemperatureC          13274895  16.572962611003668   
LastHourMinDewPointTemperatureC          13274895  15.472800726484229   
LastHourMaxRelativeHumidityPercentage    13274895    75.0567251191064   
LastHourMinRelativeHumidityPercentage    13274895   69.11167432962746   
HourlyRelativeHumidityPercentage         13274895   72.12860252378644   
HourlyWindDirectionRadiusDegrees         13274895  155.02657904262142   
MaximumWindGustMs                        13274895   4.721503288725838   
HourlyWindSpeedMs                        13274895  1.9315350064916816   
Height                                   13274895    589.997161921639   

summary                                              stddev    min    25%  \
TotalHourlyPrecipitationMm               1.2125863121400342    0.0    0.0   
HourlyStationLevelAtmosphericPressureMb   41.99265628887496  720.1  917.6   
LastHourMaxAtmosphericPressureMb          41.98374050659263  720.3  917.8   
LastHourMinAtmosphericPressureMb         42.001406956935796  720.0  917.3   
HourlyDryBulbAirTemperatureC              5.126604849432286   -7.2   18.8   
DewPointTemperatureC                      4.239247932834802  -24.9   13.4   
LastHourMaxTemperatureC                    5.25853719357768   -6.0   19.3   
LastHourMinTemperatureC                   4.987961374291914   -7.7   18.3   
LastHourMaxDewPointTemperatureC           4.174733386944118  -22.1   13.9   
LastHourMinDewPointTemperatureC           4.327098227821037  -25.0   12.8   
LastHourMaxRelativeHumidityPercentage     18.90013600655687      8     63   
LastHourMinRelativeHumidityPercentage    20.532410792951516      4     54   
HourlyRelativeHumidityPercentage         19.831565387745584      6     58   
HourlyWindDirectionRadiusDegrees          101.2654627569901      1     73   
MaximumWindGustMs                        2.8292037902012663    0.0    2.6   
HourlyWindSpeedMs                        1.5883998448755037    0.0    0.7   
Height                                     384.091689685266   2.66  305.0   

summary                                    50%    75%     max  
TotalHourlyPrecipitationMm                 0.0    0.0   100.0  
HourlyStationLevelAtmosphericPressureMb  948.2  978.4  1050.0  
LastHourMaxAtmosphericPressureMb         948.5  978.7  1050.0  
LastHourMinAtmosphericPressureMb         947.9  978.1  1047.6  
HourlyDryBulbAirTemperatureC              21.9   25.4    44.8  
DewPointTemperatureC                      16.7   19.2    37.7  
LastHourMaxTemperatureC                   22.5   26.3    45.0  
LastHourMinTemperatureC                   21.4   24.6    42.3  
LastHourMaxDewPointTemperatureC           17.2   19.7    42.2  
LastHourMinDewPointTemperatureC           16.2   18.7    36.9  
LastHourMaxRelativeHumidityPercentage       80     91     100  
LastHourMinRelativeHumidityPercentage       72     87     100  
HourlyRelativeHumidityPercentage            76     89     100  
HourlyWindDirectionRadiusDegrees           130    236     360  
MaximumWindGustMs                          4.4    6.4    50.0  
HourlyWindSpeedMs                          1.7    2.8    20.0  
Height                                   573.0  869.0  2450.0

### Estações

Esta informação já está associada a todos os dataframes, ainda assim vamos analisá-la brevemente e fazer o pré processamento caso seja necessário.

In [43]:
# Schema, show e count do DataFrame de Stations

df_stations.printSchema()
df_stations.show(5, truncate=False) 
df_stations.count()

root
 |-- station: string (nullable = true)
 |-- region: string (nullable = true)
 |-- state: string (nullable = true)
 |-- station_code: string (nullable = true)
 |-- first date: date (nullable = true)
 |-- height: double (nullable = true)
 |-- longitude: double (nullable = true)
 |-- latitude: double (nullable = true)

+---------------------------+------+-----+------------+----------+------+------------+------------+
|station                    |region|state|station_code|first date|height|longitude   |latitude    |
+---------------------------+------+-----+------------+----------+------+------------+------------+
|QUEIMADAS                  |NE    |BA   |A436        |2008-05-23|315.0 |-39.61694443|-10.984645  |
|MACAU                      |NE    |RN   |A317        |2007-01-06|32.0  |-36.57305554|-5.15111111 |
|SAQUAREMA - SAMPAIO CORREIA|SE    |RJ   |A667        |2019-01-01|26.0  |-42.60888888|-22.8711111 |
|SANTANA DO LIVRAMENTO      |S     |RS   |A804        |2001-11-22|328.0 |-55.

622

Este código exibe o esquema, as primeiras 5 linhas e conta o número total de linhas no dataframe `df_stations`, fornecendo uma visão geral da estrutura e do tamanho dos dados do datadrame das estações.

In [44]:
# há códigos repetidos porque 611 != 622
df_stations.select("station_code").distinct().count()

611

Este comando conta o número de códigos de estação únicos no DataFrame `df_stations`, indicando que há códigos de estação repetidos, pois o número de códigos distintos é menor do que o número total de registos (611 < 622).

In [45]:
# summary stats das stations
summary_stats = df_stations.summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary      count                 mean              stddev           min  \
station        622                 None                None      ABROLHOS   
region         622                 None                None            CO   
state          622                 None                None            AC   
station_code   622                 None                None          A001   
height         622   153.67808681672022  1686.8247749419163       -9999.0   
longitude      622   -48.31052870813508  7.3551386956783364  -79.49416666   
latitude       622  -15.821456649581986   8.720537558753788         -84.0   

summary                25%           50%          75%           max  
station               None          None         None       ZE DOCA  
region                None          None         None            SE  
state                 None          None         None            TO  
station_code          None          None         None          S717  
height              109.62         345.0        625.0        2450.0  
longitude     -52.85888888  -48.17333332  -42.7186111  -29.31666666  
latitude            -22.35    -16.388977  -8.77666666    4.47749999

Este bloco de código calcula as *summary stats* para todas as colunas do dataframe `df_stations`.

In [46]:
# Verificar as estações repetidas
# Agrupar por 'station_code' e contar as ocorrências
station_counts = df_stations.groupBy("station_code").agg(count("station_code").alias("count"))

# Filtrar as estações com contagem maior que 1
stations_with_more_than_one = station_counts.filter(col("count") > 1)
stations_with_more_than_one.show()

+------------+-----+
|station_code|count|
+------------+-----+
|        A618|    2|
|        A624|    2|
|        A652|    2|
|        A603|    2|
|        A667|    2|
|        A927|    2|
|        A602|    2|
|        A620|    2|
|        A621|    2|
|        A601|    2|
|        A607|    2|
+------------+-----+



Este chunk de código verifica as estações repetidas ao agrupá-las pela coluna "station_code" e ao contar as suas ocorrências. De seguida, filtra as estações com contagem maior que 1 e exibe os resultados, identificando quais as estações que estão duplicadas.

In [47]:
# verificar com algumas dessas estações porque aparecem duplicada (eram estações antigas que foram reformuladas e a localização (station) mudou ligeiramente, mas como representam a mesma estação vamos substituir os registos antigos pelos novos)
filtered_df = df_stations.filter(col("station_code") == "A927")
filtered_df.show()

+--------------------+------+-----+------------+----------+------+------------+------------+
|             station|region|state|station_code|first date|height|   longitude|    latitude|
+--------------------+------+-----+------------+----------+------+------------+------------+
|BRASNORTE (NOVO M...|    CO|   MT|        A927|2019-01-01| 426.2|-58.23138888|-12.52194443|
|BRASNORTE (MUNDO ...|    CO|   MT|        A927|2008-02-29| 431.0|-58.38722221|-12.87194443|
+--------------------+------+-----+------------+----------+------+------------+------------+



Exibe registos específicos da estação com o código "A927", permitindo uma verificação detalhada dos registos duplicados e fornecendo informações sobre as diferenças nas localizações das estações antigas e as novas.

In [48]:
# verificar os dados na tabela de metereologia para a estação acima (os dados na tabela não estão atualizados em algumas instâncias e têm aindas os valores antigos)
vef = df_central_west.filter(col("station_code") == "A927")
vef.show()

+------+----------+-----+--------------------------+---------------------------------------+--------------------------------+--------------------------------+-------------------+----------------------------+--------------------+-----------------------+-----------------------+-------------------------------+-------------------------------+-------------------------------------+-------------------------------------+--------------------------------+--------------------------------+-----------------+-----------------+------+-----+--------------------+-----------+------------+------------+------+
| Index|      Date| Hour|TotalHourlyPrecipitationMm|HourlyStationLevelAtmosphericPressureMb|LastHourMaxAtmosphericPressureMb|LastHourMinAtmosphericPressureMb|GlobalRadiationKjM2|HourlyDryBulbAirTemperatureC|DewPointTemperatureC|LastHourMaxTemperatureC|LastHourMinTemperatureC|LastHourMaxDewPointTemperatureC|LastHourMinDewPointTemperatureC|LastHourMaxRelativeHumidityPercentage|LastHourMinRelativeHumid

Exibe os dados meteorológicos associados à estação com o código "A927", permitindo uma verificação dos valores presentes na tabela de meteorologia e identificando possíveis inconsistências nos dados, como valores desatualizados.

### Concatenação dos DFs

In [70]:
# concatenação dos dataframes
concatenated_df = df_central_west.union(df_south).union(df_north).union(df_southeast).union(df_northeast)
concatenated_df.printSchema()
concatenated_df.show()
concatenated_df.count()

root
 |-- Index: integer (nullable = true)
 |-- Date: date (nullable = true)
 |-- Hour: string (nullable = true)
 |-- TotalHourlyPrecipitationMm: double (nullable = true)
 |-- HourlyStationLevelAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMaxAtmosphericPressureMb: double (nullable = true)
 |-- LastHourMinAtmosphericPressureMb: double (nullable = true)
 |-- HourlyDryBulbAirTemperatureC: double (nullable = true)
 |-- DewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxTemperatureC: double (nullable = true)
 |-- LastHourMinTemperatureC: double (nullable = true)
 |-- LastHourMaxDewPointTemperatureC: double (nullable = true)
 |-- LastHourMinDewPointTemperatureC: double (nullable = true)
 |-- LastHourMaxRelativeHumidityPercentage: integer (nullable = true)
 |-- LastHourMinRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyRelativeHumidityPercentage: integer (nullable = true)
 |-- HourlyWindDirectionRadiusDegrees: integer (nullable = true)
 |-- Maximum

49759514

Este conjunto de comandos realiza a concatenação dos dataframes `df_central_west`, `df_south`, `df_north`, `df_southeast` e `df_northeast` num único dataframe `concatenated_df`. De seguida, exibe estrutura, as primeiras linhas e devolve o número total de linhas no dataframe concatenado.

In [72]:
# summary stats do df final
summary_stats = concatenated_df.select(cols_num_2).summary().toPandas().transpose()
summary_stats.columns = summary_stats.iloc[0]
summary_stats = summary_stats[1:]
summary_stats

summary                                     count                mean  \
TotalHourlyPrecipitationMm               49759514   0.152766090118929   
HourlyStationLevelAtmosphericPressureMb  49759514   965.2958074570425   
LastHourMaxAtmosphericPressureMb         49759514   965.5655641713112   
LastHourMinAtmosphericPressureMb         49759514   965.0045343790932   
HourlyDryBulbAirTemperatureC             49759514  23.413191065330665   
DewPointTemperatureC                     49759514    17.1777642884535   
LastHourMaxTemperatureC                  49759514  24.076027058865453   
LastHourMinTemperatureC                  49759514   22.78356214049835   
LastHourMaxDewPointTemperatureC          49759514  17.721601446911173   
LastHourMinDewPointTemperatureC          49759514  16.658636929211188   
LastHourMaxRelativeHumidityPercentage    49759514    74.5965881620146   
LastHourMinRelativeHumidityPercentage    49759514   68.88761357275314   
HourlyRelativeHumidityPercentage         49759514   71.77837253394397   
HourlyWindDirectionRadiusDegrees         49759514  152.83574592388504   
MaximumWindGustMs                        49759514  4.9291405619430755   
HourlyWindSpeedMs                        49759514  2.0476139015345094   
Height                                   49759514  431.61938159237314   

summary                                              stddev    min    25%  \
TotalHourlyPrecipitationMm               1.2644366957327098    0.0    0.0   
HourlyStationLevelAtmosphericPressureMb   37.44976884102456  720.1  939.8   
LastHourMaxAtmosphericPressureMb          37.45299070576685  720.3  940.0   
LastHourMinAtmosphericPressureMb          37.43667363657928  720.0  939.5   
HourlyDryBulbAirTemperatureC              5.549682278526599   -7.7   20.1   
DewPointTemperatureC                      4.760310674870038  -27.5   14.3   
LastHourMaxTemperatureC                   5.679706125437469   -7.6   20.7   
LastHourMinTemperatureC                  5.4138710682566415   -9.5   19.6   
LastHourMaxDewPointTemperatureC           4.698454445750406  -25.1   14.9   
LastHourMinDewPointTemperatureC           4.838334265145028  -29.8   13.7   
LastHourMaxRelativeHumidityPercentage     19.32686890693644      7     62   
LastHourMinRelativeHumidityPercentage    20.811254630337903      4     54   
HourlyRelativeHumidityPercentage         20.171723980776793      6     58   
HourlyWindDirectionRadiusDegrees          98.11964361118075      1     76   
MaximumWindGustMs                        3.0622043344447465    0.0    2.6   
HourlyWindSpeedMs                        1.7171117796726179    0.0    0.7   
Height                                    346.4573319938421    0.1  126.0   

summary                                    50%    75%     max  
TotalHourlyPrecipitationMm                 0.0    0.0   100.0  
HourlyStationLevelAtmosphericPressureMb  969.6  997.0  1050.0  
LastHourMaxAtmosphericPressureMb         969.9  997.3  1050.0  
LastHourMinAtmosphericPressureMb         969.3  996.7  1049.6  
HourlyDryBulbAirTemperatureC              23.6   27.1    45.0  
DewPointTemperatureC                      18.1   20.9    44.7  
LastHourMaxTemperatureC                   24.1   27.9    45.0  
LastHourMinTemperatureC                   23.0   26.3    44.9  
LastHourMaxDewPointTemperatureC           18.6   21.3    44.7  
LastHourMinDewPointTemperatureC           17.6   20.4    44.6  
LastHourMaxRelativeHumidityPercentage       79     91     100  
LastHourMinRelativeHumidityPercentage       72     87     100  
HourlyRelativeHumidityPercentage            76     89     100  
HourlyWindDirectionRadiusDegrees           129    228     360  
MaximumWindGustMs                          4.6    6.9    99.7  
HourlyWindSpeedMs                          1.8    3.0    29.5  
Height                                   380.0  666.0  2450.0

Análise descritiva:

- A `precipitação` não é registada na maioria das horas, mas raros acontecimentos podem resultar em até 100.0 mm de precipitação numa única hora

- A `pressão atmosférica` média é cerca de 965.3 mb, com variações significativas que podem indicar mudanças climáticas

- A `temperatura` varia de -7.7 °C a 45.0 °C, o que sugere uma grande diversidade do clima ao longo do tempo

- A `humidade` relativa média é de aproximadamente 71.8%, variando de 6% a 100%

- A `velocidade do vento` média é de cerca de 2.05 m/s, com ampla variação entre ventos calmos e ventos fortes de até 29.5 m/s

- A `altitude` média registada é de 431.6 metros, sendo o valor máximo de 2450 metros. A altitude pode ser um fator influenciador das condições meteorológicas

In [71]:
# Guardar em formato parquet

output_all_stations = "all_stations.parquet"
concatenated_df.write.mode("overwrite").parquet(output_all_stations)

Este código guarda o dataframe concatenado em formato Parquet para ser utilizado nos notebooks seguintes.